### ISSUE TITLE
QUAST failed! Make sure you are using the latest version of QUAST

### ISSUE THREAD

**Issue by ZhangDengwei** [almiheenko/AGB#10]
Hi,

I installed AGB using bioconda according to your tutorial, but I consistently got the following error:

> Parsing ../H13_4/assembly_graph_with_scaffolds.gfa...
Finish parsing.
Extracting edge sequences from ../H13_4/assembly_graph_with_scaffolds.gfa...
Running QUAST...
No information about contig mappings to the reference genome
QUAST failed! Make sure you are using the latest version of QUAST
No information about edge mappings to the reference genome
Building JSON files...
Traceback (most recent call last):
  File "/home/dengwei/toolkit/anaconda/envs/AGB/bin/agb.py", line 154, in <module>
    main()
  File "/home/dengwei/toolkit/anaconda/envs/AGB/bin/agb.py", line 147, in main
    html = embed_css_and_scripts(html)
  File "/home/dengwei/toolkit/anaconda/envs/AGB/lib/python3.6/site-packages/agb_src/scripts/utils.py", line 221, in embed_css_and_scripts
    with os.io.open(fpath, 'r', encoding="utf-8") as f: contents = f.read()
AttributeError: module 'os' has no attribute 'io'

I confirmed that the version of the dependent "QUAST" was 5.0.0, then I manually updated it to 5.0.2. However, it still didn't work. May you offer any suggestion? Many thanks.

**Comment by ZhangDengwei** [comment]
I forgot attaching my command, which was 
`nohup agb.py -a SPAdes -o ./H13_4 -r GCF_000010245.2_ASM1024v1_genomic.fna -t 6 -i ../H13_4/ &`

**Comment by pbravakos** [comment]
Hi,
I am having the exact same error when trying to run agb on the fastg output of Spades with the following command

```
agb.py --graph assembly_graph_with_scaffolds.gfa -a SPAdes

```
