### ISSUE TITLE
ValueError: could not convert string to float: 'contig'

### ISSUE THREAD

**Issue by csuzhang** [almiheenko/AGB#6]
Hi:
I ran the command : $ agb.py -i assembly/canu -a canu then got the following error:
Traceback (most recent call last):
  File "/home/zhangjun/miniconda3/envs/AGB/bin/agb.py", line 154, in <module>
    main()
  File "/home/zhangjun/miniconda3/envs/AGB/bin/agb.py", line 130, in main
    opts.output_dir, opts.input_fasta, opts.min_edge_len)
  File "/home/zhangjun/miniconda3/envs/AGB/bin/agb.py", line 67, in parse_assembler_output
    dict_edges, contig_edges, edges_fpath = parse_canu_output(input_dirpath, output_dirpath, min_edge_len)
  File "/home/zhangjun/miniconda3/envs/AGB/lib/python3.6/site-packages/agb_src/scripts/info_parser.py", line 22, in parse_canu_output
    dict_edges = parse_gfa(gfa_fpath, min_edge_len, input_dirpath, assembler="canu")
  File "/home/zhangjun/miniconda3/envs/AGB/lib/python3.6/site-packages/agb_src/scripts/graph_parser.py", line 289, in parse_gfa
    dict_edges = parse_canu_unitigs_info(input_dirpath, dict_edges)
  File "/home/zhangjun/miniconda3/envs/AGB/lib/python3.6/site-packages/agb_src/scripts/graph_parser.py", line 119, in parse_canu_unitigs_info
    coverage = int(float(fs[cov_col]))
ValueError: could not convert string to float: 'contig'

Do you know what's wrong?
Thank you

**Comment by almiheenko** [comment]
Hi,

Sorry for the delay! Probably there are some discrepancies in Canu output. Could you please send me the file "*.unitigs.layout.tigInfo" from `assembly/canu` folder (at least first 100 lines)? Thank you!
